spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:45700/railway
spring.datasource.username=root
spring.datasource.password=pvCMiutXMrqdWlJSlcSPbydJUaDLROXa

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true